CREATE table USUARIO
(
NOMBRE		VARCHAR(150),
DNI			VARCHAR(9),
EDAD		INT,
CONSTRAINT 	pk_USUARIO PRIMARY KEY (DNI)
);


CREATE table OLDGEN
(
NOMBRE			VARCHAR(80),
PRECIO			DOUBLE,
GENERO			VARCHAR(20),
FORMATO			VARCHAR(20),
ALQUILADO		BIT,
PRECIOPORDIA	DOUBLE,
CONSTRAINT		pk_OLDGEN PRIMARY KEY (NOMBRE)
);

CREATE table NEWGEN
(
NOMBRE			VARCHAR(80),
PRECIO			DOUBLE,
GENERO			VARCHAR(20),
VALORACION		INT,
FECHA_SALIDA	DATE,
CONSTRAINT		pk_OLDGEN PRIMARY KEY (NOMBRE)
);


CREATE table TIENDA 
(
NOMBRE			VARCHAR(50),
DIRECCION		VARCHAR(100),
CONSTRAINT		pk_TIENDA PRIMARY KEY (NOMBRE)
);


ALTER TABLE USUARIO ADD NOMBRE_TIENDA VARCHAR(50);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO FOREIGN KEY (NOMBRE_TIENDA) REFERENCES TIENDA (NOMBRE);


